/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsolePathRouteImport } from './routes/$consolePath'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as URouteImport } from './routes/u'
import { Route as ConsolePathIndexRouteImport } from './routes/$consolePath/index'
import { Route as ConsolePathLoginRouteImport } from './routes/$consolePath/login'
import { Route as ConsolePathSettingsRouteImport } from './routes/$consolePath/settings'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountAnalyticsRouteImport } from './routes/account/analytics'
import { Route as AccountDiagramsRouteImport } from './routes/account/diagrams'
import { Route as AccountEmailRouteImport } from './routes/account/email'
import { Route as AccountFailedRouteImport } from './routes/account/failed'
import { Route as AccountForgotRouteImport } from './routes/account/forgot'
import { Route as AccountGuideRouteImport } from './routes/account/guide'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as AccountNotificationsRouteImport } from './routes/account/notifications'
import { Route as AccountOrdersRouteImport } from './routes/account/orders'
import { Route as AccountReturnsRouteImport } from './routes/account/returns'
import { Route as AccountRoutingRouteImport } from './routes/account/routing'
import { Route as AccountSftpRouteImport } from './routes/account/sftp'
import { Route as AccountTeamRouteImport } from './routes/account/team'
import { Route as AccountWarehousesRouteImport } from './routes/account/warehouses'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetTokenRouteImport } from './routes/reset.$token'
import { Route as UIndexRouteImport } from './routes/u/index'
import { Route as ULoginRouteImport } from './routes/u/login'
import { Route as ConsolePathCompaniesCompanyIdRouteImport } from './routes/$consolePath/companies.$companyId'
import { Route as ConsolePathShopsShopIdRouteImport } from './routes/$consolePath/shops.$shopId'
import { Route as AccountOrdersIndexRouteImport } from './routes/account/orders.index'
import { Route as AccountOrdersOrderIdRouteImport } from './routes/account/orders.$orderId'
import { Route as AccountWarehousesIndexRouteImport } from './routes/account/warehouses.index'
import { Route as AccountWarehousesWarehouseIdRouteImport } from './routes/account/warehouses.$warehouseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePathRoute = ConsolePathRouteImport.update({
  id: '/$consolePath',
  path: '/$consolePath',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const URoute = URouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePathIndexRoute = ConsolePathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsolePathRoute,
} as any)
const ConsolePathLoginRoute = ConsolePathLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsolePathRoute,
} as any)
const ConsolePathSettingsRoute = ConsolePathSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsolePathRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAnalyticsRoute = AccountAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDiagramsRoute = AccountDiagramsRouteImport.update({
  id: '/diagrams',
  path: '/diagrams',
  getParentRoute: () => AccountRoute,
} as any)
const AccountEmailRoute = AccountEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AccountRoute,
} as any)
const AccountFailedRoute = AccountFailedRouteImport.update({
  id: '/failed',
  path: '/failed',
  getParentRoute: () => AccountRoute,
} as any)
const AccountForgotRoute = AccountForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AccountRoute,
} as any)
const AccountGuideRoute = AccountGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AccountRoute,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRoutingRoute = AccountRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSftpRoute = AccountSftpRouteImport.update({
  id: '/sftp',
  path: '/sftp',
  getParentRoute: () => AccountRoute,
} as any)
const AccountTeamRoute = AccountTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AccountRoute,
} as any)
const AccountWarehousesRoute = AccountWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AccountRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTokenRoute = ResetTokenRouteImport.update({
  id: '/reset/$token',
  path: '/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => URoute,
} as any)
const ULoginRoute = ULoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => URoute,
} as any)
const ConsolePathCompaniesCompanyIdRoute =
  ConsolePathCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => ConsolePathRoute,
  } as any)
const ConsolePathShopsShopIdRoute = ConsolePathShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => ConsolePathRoute,
} as any)
const AccountOrdersIndexRoute = AccountOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountOrdersOrderIdRoute = AccountOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => AccountOrdersRoute,
} as any)
const AccountWarehousesIndexRoute = AccountWarehousesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountWarehousesRoute,
} as any)
const AccountWarehousesWarehouseIdRoute =
  AccountWarehousesWarehouseIdRouteImport.update({
    id: '/$warehouseId',
    path: '/$warehouseId',
    getParentRoute: () => AccountWarehousesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$consolePath': typeof ConsolePathRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/u': typeof URouteWithChildren
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/$consolePath/settings': typeof ConsolePathSettingsRoute
  '/account/analytics': typeof AccountAnalyticsRoute
  '/account/diagrams': typeof AccountDiagramsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/failed': typeof AccountFailedRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/guide': typeof AccountGuideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/returns': typeof AccountReturnsRoute
  '/account/routing': typeof AccountRoutingRoute
  '/account/sftp': typeof AccountSftpRoute
  '/account/team': typeof AccountTeamRoute
  '/account/warehouses': typeof AccountWarehousesRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath/': typeof ConsolePathIndexRoute
  '/account/': typeof AccountIndexRoute
  '/u/': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/warehouses/$warehouseId': typeof AccountWarehousesWarehouseIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/warehouses/': typeof AccountWarehousesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/$consolePath/settings': typeof ConsolePathSettingsRoute
  '/account/analytics': typeof AccountAnalyticsRoute
  '/account/diagrams': typeof AccountDiagramsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/failed': typeof AccountFailedRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/guide': typeof AccountGuideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/routing': typeof AccountRoutingRoute
  '/account/sftp': typeof AccountSftpRoute
  '/account/team': typeof AccountTeamRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath': typeof ConsolePathIndexRoute
  '/account': typeof AccountIndexRoute
  '/u': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/warehouses/$warehouseId': typeof AccountWarehousesWarehouseIdRoute
  '/account/orders': typeof AccountOrdersIndexRoute
  '/account/warehouses': typeof AccountWarehousesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$consolePath': typeof ConsolePathRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/u': typeof URouteWithChildren
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/$consolePath/settings': typeof ConsolePathSettingsRoute
  '/account/analytics': typeof AccountAnalyticsRoute
  '/account/diagrams': typeof AccountDiagramsRoute
  '/account/email': typeof AccountEmailRoute
  '/account/failed': typeof AccountFailedRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/guide': typeof AccountGuideRoute
  '/account/login': typeof AccountLoginRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRouteWithChildren
  '/account/returns': typeof AccountReturnsRoute
  '/account/routing': typeof AccountRoutingRoute
  '/account/sftp': typeof AccountSftpRoute
  '/account/team': typeof AccountTeamRoute
  '/account/warehouses': typeof AccountWarehousesRouteWithChildren
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath/': typeof ConsolePathIndexRoute
  '/account/': typeof AccountIndexRoute
  '/u/': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
  '/account/orders/$orderId': typeof AccountOrdersOrderIdRoute
  '/account/warehouses/$warehouseId': typeof AccountWarehousesWarehouseIdRoute
  '/account/orders/': typeof AccountOrdersIndexRoute
  '/account/warehouses/': typeof AccountWarehousesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$consolePath'
    | '/about'
    | '/account'
    | '/login'
    | '/signup'
    | '/u'
    | '/$consolePath/login'
    | '/$consolePath/settings'
    | '/account/analytics'
    | '/account/diagrams'
    | '/account/email'
    | '/account/failed'
    | '/account/forgot'
    | '/account/guide'
    | '/account/login'
    | '/account/notifications'
    | '/account/orders'
    | '/account/returns'
    | '/account/routing'
    | '/account/sftp'
    | '/account/team'
    | '/account/warehouses'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath/'
    | '/account/'
    | '/u/'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
    | '/account/orders/$orderId'
    | '/account/warehouses/$warehouseId'
    | '/account/orders/'
    | '/account/warehouses/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/signup'
    | '/$consolePath/login'
    | '/$consolePath/settings'
    | '/account/analytics'
    | '/account/diagrams'
    | '/account/email'
    | '/account/failed'
    | '/account/forgot'
    | '/account/guide'
    | '/account/login'
    | '/account/notifications'
    | '/account/returns'
    | '/account/routing'
    | '/account/sftp'
    | '/account/team'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath'
    | '/account'
    | '/u'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
    | '/account/orders/$orderId'
    | '/account/warehouses/$warehouseId'
    | '/account/orders'
    | '/account/warehouses'
  id:
    | '__root__'
    | '/'
    | '/$consolePath'
    | '/about'
    | '/account'
    | '/login'
    | '/signup'
    | '/u'
    | '/$consolePath/login'
    | '/$consolePath/settings'
    | '/account/analytics'
    | '/account/diagrams'
    | '/account/email'
    | '/account/failed'
    | '/account/forgot'
    | '/account/guide'
    | '/account/login'
    | '/account/notifications'
    | '/account/orders'
    | '/account/returns'
    | '/account/routing'
    | '/account/sftp'
    | '/account/team'
    | '/account/warehouses'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath/'
    | '/account/'
    | '/u/'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
    | '/account/orders/$orderId'
    | '/account/warehouses/$warehouseId'
    | '/account/orders/'
    | '/account/warehouses/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsolePathRoute: typeof ConsolePathRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  URoute: typeof URouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ResetTokenRoute: typeof ResetTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$consolePath': {
      id: '/$consolePath'
      path: '/$consolePath'
      fullPath: '/$consolePath'
      preLoaderRoute: typeof ConsolePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$consolePath/': {
      id: '/$consolePath/'
      path: '/'
      fullPath: '/$consolePath/'
      preLoaderRoute: typeof ConsolePathIndexRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/$consolePath/login': {
      id: '/$consolePath/login'
      path: '/login'
      fullPath: '/$consolePath/login'
      preLoaderRoute: typeof ConsolePathLoginRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/$consolePath/settings': {
      id: '/$consolePath/settings'
      path: '/settings'
      fullPath: '/$consolePath/settings'
      preLoaderRoute: typeof ConsolePathSettingsRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/analytics': {
      id: '/account/analytics'
      path: '/analytics'
      fullPath: '/account/analytics'
      preLoaderRoute: typeof AccountAnalyticsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/diagrams': {
      id: '/account/diagrams'
      path: '/diagrams'
      fullPath: '/account/diagrams'
      preLoaderRoute: typeof AccountDiagramsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/email': {
      id: '/account/email'
      path: '/email'
      fullPath: '/account/email'
      preLoaderRoute: typeof AccountEmailRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/failed': {
      id: '/account/failed'
      path: '/failed'
      fullPath: '/account/failed'
      preLoaderRoute: typeof AccountFailedRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/forgot': {
      id: '/account/forgot'
      path: '/forgot'
      fullPath: '/account/forgot'
      preLoaderRoute: typeof AccountForgotRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/guide': {
      id: '/account/guide'
      path: '/guide'
      fullPath: '/account/guide'
      preLoaderRoute: typeof AccountGuideRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/orders': {
      id: '/account/orders'
      path: '/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/returns': {
      id: '/account/returns'
      path: '/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/routing': {
      id: '/account/routing'
      path: '/routing'
      fullPath: '/account/routing'
      preLoaderRoute: typeof AccountRoutingRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/sftp': {
      id: '/account/sftp'
      path: '/sftp'
      fullPath: '/account/sftp'
      preLoaderRoute: typeof AccountSftpRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/team': {
      id: '/account/team'
      path: '/team'
      fullPath: '/account/team'
      preLoaderRoute: typeof AccountTeamRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/warehouses': {
      id: '/account/warehouses'
      path: '/warehouses'
      fullPath: '/account/warehouses'
      preLoaderRoute: typeof AccountWarehousesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$token': {
      id: '/reset/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof ResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof URoute
    }
    '/u/login': {
      id: '/u/login'
      path: '/login'
      fullPath: '/u/login'
      preLoaderRoute: typeof ULoginRouteImport
      parentRoute: typeof URoute
    }
    '/$consolePath/companies/$companyId': {
      id: '/$consolePath/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/$consolePath/companies/$companyId'
      preLoaderRoute: typeof ConsolePathCompaniesCompanyIdRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/$consolePath/shops/$shopId': {
      id: '/$consolePath/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/$consolePath/shops/$shopId'
      preLoaderRoute: typeof ConsolePathShopsShopIdRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/account/orders/': {
      id: '/account/orders/'
      path: '/'
      fullPath: '/account/orders/'
      preLoaderRoute: typeof AccountOrdersIndexRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/orders/$orderId': {
      id: '/account/orders/$orderId'
      path: '/$orderId'
      fullPath: '/account/orders/$orderId'
      preLoaderRoute: typeof AccountOrdersOrderIdRouteImport
      parentRoute: typeof AccountOrdersRoute
    }
    '/account/warehouses/': {
      id: '/account/warehouses/'
      path: '/'
      fullPath: '/account/warehouses/'
      preLoaderRoute: typeof AccountWarehousesIndexRouteImport
      parentRoute: typeof AccountWarehousesRoute
    }
    '/account/warehouses/$warehouseId': {
      id: '/account/warehouses/$warehouseId'
      path: '/$warehouseId'
      fullPath: '/account/warehouses/$warehouseId'
      preLoaderRoute: typeof AccountWarehousesWarehouseIdRouteImport
      parentRoute: typeof AccountWarehousesRoute
    }
  }
}

interface ConsolePathRouteChildren {
  ConsolePathLoginRoute: typeof ConsolePathLoginRoute
  ConsolePathSettingsRoute: typeof ConsolePathSettingsRoute
  ConsolePathIndexRoute: typeof ConsolePathIndexRoute
  ConsolePathCompaniesCompanyIdRoute: typeof ConsolePathCompaniesCompanyIdRoute
  ConsolePathShopsShopIdRoute: typeof ConsolePathShopsShopIdRoute
}

const ConsolePathRouteChildren: ConsolePathRouteChildren = {
  ConsolePathLoginRoute: ConsolePathLoginRoute,
  ConsolePathSettingsRoute: ConsolePathSettingsRoute,
  ConsolePathIndexRoute: ConsolePathIndexRoute,
  ConsolePathCompaniesCompanyIdRoute: ConsolePathCompaniesCompanyIdRoute,
  ConsolePathShopsShopIdRoute: ConsolePathShopsShopIdRoute,
}

const ConsolePathRouteWithChildren = ConsolePathRoute._addFileChildren(
  ConsolePathRouteChildren,
)

interface AccountOrdersRouteChildren {
  AccountOrdersOrderIdRoute: typeof AccountOrdersOrderIdRoute
  AccountOrdersIndexRoute: typeof AccountOrdersIndexRoute
}

const AccountOrdersRouteChildren: AccountOrdersRouteChildren = {
  AccountOrdersOrderIdRoute: AccountOrdersOrderIdRoute,
  AccountOrdersIndexRoute: AccountOrdersIndexRoute,
}

const AccountOrdersRouteWithChildren = AccountOrdersRoute._addFileChildren(
  AccountOrdersRouteChildren,
)

interface AccountWarehousesRouteChildren {
  AccountWarehousesWarehouseIdRoute: typeof AccountWarehousesWarehouseIdRoute
  AccountWarehousesIndexRoute: typeof AccountWarehousesIndexRoute
}

const AccountWarehousesRouteChildren: AccountWarehousesRouteChildren = {
  AccountWarehousesWarehouseIdRoute: AccountWarehousesWarehouseIdRoute,
  AccountWarehousesIndexRoute: AccountWarehousesIndexRoute,
}

const AccountWarehousesRouteWithChildren =
  AccountWarehousesRoute._addFileChildren(AccountWarehousesRouteChildren)

interface AccountRouteChildren {
  AccountAnalyticsRoute: typeof AccountAnalyticsRoute
  AccountDiagramsRoute: typeof AccountDiagramsRoute
  AccountEmailRoute: typeof AccountEmailRoute
  AccountFailedRoute: typeof AccountFailedRoute
  AccountForgotRoute: typeof AccountForgotRoute
  AccountGuideRoute: typeof AccountGuideRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRouteWithChildren
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountRoutingRoute: typeof AccountRoutingRoute
  AccountSftpRoute: typeof AccountSftpRoute
  AccountTeamRoute: typeof AccountTeamRoute
  AccountWarehousesRoute: typeof AccountWarehousesRouteWithChildren
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAnalyticsRoute: AccountAnalyticsRoute,
  AccountDiagramsRoute: AccountDiagramsRoute,
  AccountEmailRoute: AccountEmailRoute,
  AccountFailedRoute: AccountFailedRoute,
  AccountForgotRoute: AccountForgotRoute,
  AccountGuideRoute: AccountGuideRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRouteWithChildren,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountRoutingRoute: AccountRoutingRoute,
  AccountSftpRoute: AccountSftpRoute,
  AccountTeamRoute: AccountTeamRoute,
  AccountWarehousesRoute: AccountWarehousesRouteWithChildren,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface URouteChildren {
  ULoginRoute: typeof ULoginRoute
  UIndexRoute: typeof UIndexRoute
}

const URouteChildren: URouteChildren = {
  ULoginRoute: ULoginRoute,
  UIndexRoute: UIndexRoute,
}

const URouteWithChildren = URoute._addFileChildren(URouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsolePathRoute: ConsolePathRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  URoute: URouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ResetTokenRoute: ResetTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
