# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

#client_id = "821f120c5486b63127be03f1a4cdc102"
client_id = "563cf41146d7f10bae04f37953d3168e"
name = "wms-app"


application_url = "https://wms-demo-backend.integritistudio.us/api/shopify/app"
embedded = true

[build]
automatically_update_urls_on_dev = false

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  uri = "https://wms-demo-backend.integritistudio.us/api/shopify/webhooks"
  topics = [ "orders/cancelled", "orders/create", "app/uninstalled" ]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_merchant_managed_fulfillment_orders,read_orders,write_fulfillments,write_merchant_managed_fulfillment_orders"

[auth]
redirect_urls = [
  "https://wms-demo-backend.integritistudio.us/api/shopify/auth",
  "https://wms-demo-backend.integritistudio.us/api/shopify/auth/callback"
]
