/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsolePathRouteImport } from './routes/$consolePath'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as LoginRouteImport } from './routes/login'
import { Route as URouteImport } from './routes/u'
import { Route as ConsolePathIndexRouteImport } from './routes/$consolePath/index'
import { Route as ConsolePathLoginRouteImport } from './routes/$consolePath/login'
import { Route as AccountIndexRouteImport } from './routes/account/index'
import { Route as AccountForgotRouteImport } from './routes/account/forgot'
import { Route as AccountLoginRouteImport } from './routes/account/login'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as ResetTokenRouteImport } from './routes/reset.$token'
import { Route as UIndexRouteImport } from './routes/u/index'
import { Route as ULoginRouteImport } from './routes/u/login'
import { Route as ConsolePathCompaniesCompanyIdRouteImport } from './routes/$consolePath/companies.$companyId'
import { Route as ConsolePathShopsShopIdRouteImport } from './routes/$consolePath/shops.$shopId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePathRoute = ConsolePathRouteImport.update({
  id: '/$consolePath',
  path: '/$consolePath',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const URoute = URouteImport.update({
  id: '/u',
  path: '/u',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsolePathIndexRoute = ConsolePathIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsolePathRoute,
} as any)
const ConsolePathLoginRoute = ConsolePathLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ConsolePathRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountForgotRoute = AccountForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AccountRoute,
} as any)
const AccountLoginRoute = AccountLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AccountRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetTokenRoute = ResetTokenRouteImport.update({
  id: '/reset/$token',
  path: '/reset/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const UIndexRoute = UIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => URoute,
} as any)
const ULoginRoute = ULoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => URoute,
} as any)
const ConsolePathCompaniesCompanyIdRoute =
  ConsolePathCompaniesCompanyIdRouteImport.update({
    id: '/companies/$companyId',
    path: '/companies/$companyId',
    getParentRoute: () => ConsolePathRoute,
  } as any)
const ConsolePathShopsShopIdRoute = ConsolePathShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => ConsolePathRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$consolePath': typeof ConsolePathRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/u': typeof URouteWithChildren
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath/': typeof ConsolePathIndexRoute
  '/account/': typeof AccountIndexRoute
  '/u/': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath': typeof ConsolePathIndexRoute
  '/account': typeof AccountIndexRoute
  '/u': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$consolePath': typeof ConsolePathRouteWithChildren
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/login': typeof LoginRoute
  '/u': typeof URouteWithChildren
  '/$consolePath/login': typeof ConsolePathLoginRoute
  '/account/forgot': typeof AccountForgotRoute
  '/account/login': typeof AccountLoginRoute
  '/invite/$token': typeof InviteTokenRoute
  '/reset/$token': typeof ResetTokenRoute
  '/u/login': typeof ULoginRoute
  '/$consolePath/': typeof ConsolePathIndexRoute
  '/account/': typeof AccountIndexRoute
  '/u/': typeof UIndexRoute
  '/$consolePath/companies/$companyId': typeof ConsolePathCompaniesCompanyIdRoute
  '/$consolePath/shops/$shopId': typeof ConsolePathShopsShopIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$consolePath'
    | '/about'
    | '/account'
    | '/login'
    | '/u'
    | '/$consolePath/login'
    | '/account/forgot'
    | '/account/login'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath/'
    | '/account/'
    | '/u/'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/$consolePath/login'
    | '/account/forgot'
    | '/account/login'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath'
    | '/account'
    | '/u'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
  id:
    | '__root__'
    | '/'
    | '/$consolePath'
    | '/about'
    | '/account'
    | '/login'
    | '/u'
    | '/$consolePath/login'
    | '/account/forgot'
    | '/account/login'
    | '/invite/$token'
    | '/reset/$token'
    | '/u/login'
    | '/$consolePath/'
    | '/account/'
    | '/u/'
    | '/$consolePath/companies/$companyId'
    | '/$consolePath/shops/$shopId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsolePathRoute: typeof ConsolePathRouteWithChildren
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRouteWithChildren
  LoginRoute: typeof LoginRoute
  URoute: typeof URouteWithChildren
  InviteTokenRoute: typeof InviteTokenRoute
  ResetTokenRoute: typeof ResetTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$consolePath': {
      id: '/$consolePath'
      path: '/$consolePath'
      fullPath: '/$consolePath'
      preLoaderRoute: typeof ConsolePathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u': {
      id: '/u'
      path: '/u'
      fullPath: '/u'
      preLoaderRoute: typeof URouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$consolePath/': {
      id: '/$consolePath/'
      path: '/'
      fullPath: '/$consolePath/'
      preLoaderRoute: typeof ConsolePathIndexRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/$consolePath/login': {
      id: '/$consolePath/login'
      path: '/login'
      fullPath: '/$consolePath/login'
      preLoaderRoute: typeof ConsolePathLoginRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/forgot': {
      id: '/account/forgot'
      path: '/forgot'
      fullPath: '/account/forgot'
      preLoaderRoute: typeof AccountForgotRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/login': {
      id: '/account/login'
      path: '/login'
      fullPath: '/account/login'
      preLoaderRoute: typeof AccountLoginRouteImport
      parentRoute: typeof AccountRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset/$token': {
      id: '/reset/$token'
      path: '/reset/$token'
      fullPath: '/reset/$token'
      preLoaderRoute: typeof ResetTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/': {
      id: '/u/'
      path: '/'
      fullPath: '/u/'
      preLoaderRoute: typeof UIndexRouteImport
      parentRoute: typeof URoute
    }
    '/u/login': {
      id: '/u/login'
      path: '/login'
      fullPath: '/u/login'
      preLoaderRoute: typeof ULoginRouteImport
      parentRoute: typeof URoute
    }
    '/$consolePath/companies/$companyId': {
      id: '/$consolePath/companies/$companyId'
      path: '/companies/$companyId'
      fullPath: '/$consolePath/companies/$companyId'
      preLoaderRoute: typeof ConsolePathCompaniesCompanyIdRouteImport
      parentRoute: typeof ConsolePathRoute
    }
    '/$consolePath/shops/$shopId': {
      id: '/$consolePath/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/$consolePath/shops/$shopId'
      preLoaderRoute: typeof ConsolePathShopsShopIdRouteImport
      parentRoute: typeof ConsolePathRoute
    }
  }
}

interface ConsolePathRouteChildren {
  ConsolePathLoginRoute: typeof ConsolePathLoginRoute
  ConsolePathIndexRoute: typeof ConsolePathIndexRoute
  ConsolePathCompaniesCompanyIdRoute: typeof ConsolePathCompaniesCompanyIdRoute
  ConsolePathShopsShopIdRoute: typeof ConsolePathShopsShopIdRoute
}

const ConsolePathRouteChildren: ConsolePathRouteChildren = {
  ConsolePathLoginRoute: ConsolePathLoginRoute,
  ConsolePathIndexRoute: ConsolePathIndexRoute,
  ConsolePathCompaniesCompanyIdRoute: ConsolePathCompaniesCompanyIdRoute,
  ConsolePathShopsShopIdRoute: ConsolePathShopsShopIdRoute,
}

const ConsolePathRouteWithChildren = ConsolePathRoute._addFileChildren(
  ConsolePathRouteChildren,
)

interface AccountRouteChildren {
  AccountForgotRoute: typeof AccountForgotRoute
  AccountLoginRoute: typeof AccountLoginRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountForgotRoute: AccountForgotRoute,
  AccountLoginRoute: AccountLoginRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface URouteChildren {
  ULoginRoute: typeof ULoginRoute
  UIndexRoute: typeof UIndexRoute
}

const URouteChildren: URouteChildren = {
  ULoginRoute: ULoginRoute,
  UIndexRoute: UIndexRoute,
}

const URouteWithChildren = URoute._addFileChildren(URouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsolePathRoute: ConsolePathRouteWithChildren,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRouteWithChildren,
  LoginRoute: LoginRoute,
  URoute: URouteWithChildren,
  InviteTokenRoute: InviteTokenRoute,
  ResetTokenRoute: ResetTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
